# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Michitaro Koike
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab-stellar-globe
project_short_description: ''
python_name: stellarglobe
repository: ''
test: true

