// typeValidators.js will be generated by jlpm run refresh-jsonschema
// @ts-ignore
import * as validators from './typeValidators'

export class TypeGuardError extends Error { }


export function catchTypeGuardError(cb: () => void) {
  try {
    cb()
  }
  catch (e) {
    if (e instanceof TypeGuardError) {
      alert(e.message)
    }
    else {
      throw e
    }
  }
}


export function createIs<Type>(validatorName: keyof typeof validators) {
  function is(
    obj: any,
  ): obj is Type {
    const v = validators[validatorName]
    if (!v) {
      // @ts-ignore
      throw new Error(`Validator not found: ${validatorName}`)
    }
    const ok = v(obj)
    if (!ok) {
      Object.assign(is, { errors: (v as any).errors as string[] })
    }
    return ok
  }
  return Object.assign(is, { errors: [] as string[] })
}


export function createAssert<Type>(validatorName: keyof typeof validators) {
  function assert(
    obj: any,
  ): asserts obj is Type {
    const v = validators[validatorName]
    if (!v) {
      // @ts-ignore
      throw new Error(`Validator not found: ${validatorName}`)
    }
    if (!v(obj)) {
      console.error(obj)
      // @ts-ignore
      throw new TypeGuardError(`TypeError for ${validatorName}\n${JSON.stringify(v.errors, null, 2)}`)
    }
  }
  return assert
}
