build: build-app build-public-jsonschema

build-app: build-toapp-typevalidator build-action-typevalidator
	npm run build

build-toapp-typevalidator:
	npm run make-toapp-typevalidator

build-action-typevalidator:
	npm run make-action-typevalidator

build-public-jsonschema:
	npm run make-public-json-schema
