import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

from .base import CommBase, remove_none

comm_target = 'stellarglobe/new'


@dataclass
class JupyterLabCommOptions:
    pass


class JupyterLabComm(CommBase):  # pragma: no cover
    def __init__(self, initial_msg, options: JupyterLabCommOptions) -> None:
        self._comm = create_comm(comm_target, remove_none(initial_msg))

    def send(self, msg):
        self._comm.send(remove_none(msg))

    def on_msg(self, callback):
        def unwarp_callback(raw_msg):
            msg = raw_msg['content']['data']
            callback(msg)

        self._comm.on_msg(unwarp_callback)

    def wait_for_query_response_text(self, query_id: str) -> str:
        # The response file is generated by the jupyterlab extension
        #
        # expected response file format:
        #   <size>\n<text>
        #
        # where <size> is the number of characters in <text> (in decimal)
        # and <text> is the response text
        #
        timeout = 10
        poll_interval = 0.1

        deadline = time.time() + timeout
        response_file = f'~query-{query_id}'
        while time.time() <= deadline:
            parent = Path(response_file).absolute().parent
            while True:
                p = parent / response_file
                try:
                    with open(p) as f:
                        size_str = f.readline()
                        if size_str[-1] != '\n':
                            raise ValueError("Invalid response file format")
                        response = f.read()
                        if len(response) == int(size_str):
                            return response
                except (ValueError, FileNotFoundError):
                    pass
                finally:
                    p.unlink(missing_ok=True)
                if parent == parent.parent:
                    break
                parent = parent.parent
            time.sleep(poll_interval)
        raise TimeoutError()


def create_comm(target: str, initial_msg):  # pragma: no cover
    try:
        from comm import create_comm  # type: ignore

    except ImportError:
        from ipykernel.comm import Comm  # type: ignore

        return Comm(target, initial_msg)
    else:
        return create_comm(target, initial_msg)
