import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, AsyncIterable, Callable, Literal, Optional, Tuple, TypedDict, Union, cast

from hscmap.models.Open import Model as Open

from .base import CommBase, remove_none

comm_target = 'stellarglobe/new'


@dataclass
class JupyterLabCommOptions:
    pass


class JupyterLabComm(CommBase):  # pragma: no cover
    def __init__(self, open_msg: Open, options: JupyterLabCommOptions) -> None:
        self._extra_options = extra_options()
        open_msg['extraOptions'] = self._extra_options  # type: ignore
        self._comm = create_comm(comm_target, remove_none(open_msg))

    def send(self, msg):
        self._comm.send(remove_none(msg))

    def on_msg(self, callback):
        def unwarp_callback(raw_msg):
            msg = raw_msg['content']['data']
            callback(msg)

        self._comm.on_msg(unwarp_callback)

    def wait_for_query_response_text(self, query_id: str) -> str:
        # The response is generated by the jupyterlab extension
        #
        # expected file response format:
        #   <size>\n<text>
        #
        # where <size> is the number of characters in <text> (in decimal)
        # and <text> is the response text
        #
        timeout = 10
        poll_interval = 0.1

        deadline = time.time() + timeout
        response_file = f'~query-{query_id}'
        while time.time() <= deadline:
            for parent in candidate_dirs(response_file):
                list(parent.glob('*'))  # This is a bit tricky, but in the JupyterLite environment, if you don't do this, newly created files won't be visible.
                p = parent / response_file
                try:
                    with open(p) as f:
                        size_str = f.readline()
                        if size_str[-1] != '\n':
                            raise ValueError("Invalid response file format")
                        response = f.read()
                        if len(response) == int(size_str):
                            p.unlink(missing_ok=True)
                            return response
                except:
                    pass
            time.sleep(poll_interval)
        raise TimeoutError()


# These parts need to be consistent with the jupyterlab extension


class FileStorageOptions(TypedDict):
    type: Literal['file']


RuntimeType = Literal['python', 'pyodide']


class ExtraOptions(TypedDict):
    storage: FileStorageOptions
    runtime: RuntimeType


def extra_options() -> ExtraOptions:
    return {
        'storage': {'type': 'file'},
        'runtime': 'pyodide' if sys.platform == 'emscripten' else 'python',
    }


def candidate_dirs(response_file: str):
    checked = set()
    seeds = [
        Path(response_file).absolute().parent,
        Path('/drive'),
        Path('/home/pyodide'),
        Path('/'),
    ]
    for seed in seeds:
        parent = seed
        while True:
            resolved = str(parent)
            if resolved not in checked:
                checked.add(resolved)
                yield parent
            if parent == parent.parent:
                break
            parent = parent.parent

def create_comm(target: str, initial_msg):  # pragma: no cover
    f: Optional[Callable] = None
    if f is None:
        try:
            from comm import create_comm  # type: ignore

            f = create_comm
        except ImportError:
            pass
    if f is None:
        try:
            from ipykernel.comm import Comm  # type: ignore

            f = Comm
        except ImportError:
            pass
    if f is None:
        raise ImportError('No available comm module')
    return f(target, initial_msg)
