import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, AsyncIterable, Callable, Literal, Optional, Tuple, TypedDict, Union, cast

from hscmap.models.Open import Model as Open

from .base import CommBase, remove_none

comm_target = 'stellarglobe/new'
query_response_indexeddb_name = 'stellar-globe-query-responses'
query_response_indexeddb_store = 'responses'
_run_sync_supported: Optional[bool] = None


@dataclass
class JupyterLabCommOptions:
    pass


class JupyterLabComm(CommBase):  # pragma: no cover
    def __init__(self, open_msg: Open, options: JupyterLabCommOptions) -> None:
        self._extra_options = extra_options()
        self._query_responses: dict[str, str] = {}
        open_msg['extraOptions'] = self._extra_options  # type: ignore
        self._comm = create_comm(comm_target, remove_none(open_msg))

    def send(self, msg):
        self._comm.send(remove_none(msg))

    def on_msg(self, callback):
        def unwarp_callback(raw_msg):
            msg = raw_msg['content']['data']
            if msg.get('type') == '__query_response__':
                query_id = msg.get('queryId')
                content = msg.get('content')
                if isinstance(query_id, str) and isinstance(content, str):
                    self._query_responses[query_id] = content
                    return
            callback(msg)

        self._comm.on_msg(unwarp_callback)

    def wait_for_query_response_text(self, query_id: str) -> str:
        # The response is generated by the jupyterlab extension
        #
        # expected file response format:
        #   <size>\n<text>
        #
        # where <size> is the number of characters in <text> (in decimal)
        # and <text> is the response text
        #
        timeout = 10
        poll_interval = 0.1

        deadline = time.time() + timeout
        response_file = query_response_filename(query_id)
        insecure_pyodide = sys.platform == 'emscripten' and not is_secure_context()
        use_indexeddb = insecure_pyodide and supports_blocking_js_promise_wait()
        while time.time() <= deadline:
            cached = self._query_responses.pop(query_id, None)
            if cached is not None:
                return cached
            if use_indexeddb:
                try:
                    indexeddb_response = load_query_response_from_indexeddb(query_id)
                except Exception:
                    indexeddb_response = None
                if indexeddb_response is not None:
                    return indexeddb_response
            for parent in candidate_dirs(response_file):
                list(parent.glob('*'))  # This is a bit tricky, but in the JupyterLite environment, if you don't do this, newly created files won't be visible.
                list(parent.glob('.*'))
                p = parent / response_file
                try:
                    with open(p) as f:
                        size_str = f.readline()
                        if size_str[-1] != '\n':
                            raise ValueError("Invalid response file format")
                        response = f.read()
                        if len(response) == int(size_str):
                            p.unlink(missing_ok=True)
                            return response
                except:
                    pass
            time.sleep(poll_interval)
        if insecure_pyodide and not use_indexeddb:
            raise unsupported_nonsecure_query_response_runtime()
        raise TimeoutError()


# These parts need to be consistent with the jupyterlab extension


class FileStorageOptions(TypedDict):
    type: Literal['file']


RuntimeType = Literal['python', 'pyodide']


class ExtraOptions(TypedDict):
    storage: FileStorageOptions
    runtime: RuntimeType


def extra_options() -> ExtraOptions:
    return {
        'storage': {'type': 'file'},
        'runtime': 'pyodide' if sys.platform == 'emscripten' else 'python',
    }


def candidate_dirs(response_file: str):
    checked = set()
    seeds = [
        Path(response_file).absolute().parent,
        Path('/drive'),
        Path('/home/pyodide'),
        Path('/'),
    ]
    for seed in seeds:
        parent = seed
        while True:
            resolved = str(parent)
            if resolved not in checked:
                checked.add(resolved)
                yield parent
            if parent == parent.parent:
                break
            parent = parent.parent


def is_secure_context() -> bool:
    try:
        import js  # type: ignore
    except ImportError:
        return False
    return bool(getattr(js, 'isSecureContext', False))


def query_response_filename(query_id: str) -> str:
    return f'.query-{query_id}' if sys.platform == 'emscripten' else f'~query-{query_id}'


def unsupported_nonsecure_query_response_runtime() -> RuntimeError:
    return RuntimeError(
        'This JupyterLite runtime cannot block on browser promises on a non-secure origin. '
        'Window(), sync(), and snapshot_bytes() need HTTPS/localhost or a browser runtime '
        'with WebAssembly stack switching support.'
    )


def load_query_response_from_indexeddb(query_id: str) -> Optional[str]:
    from pyodide.ffi import create_once_callable, run_sync  # type: ignore
    import js  # type: ignore

    if not supports_blocking_js_promise_wait():
        raise unsupported_nonsecure_query_response_runtime()

    async def load() -> Optional[str]:
        open_request = js.indexedDB.open(query_response_indexeddb_name, 1)
        open_request.onupgradeneeded = create_once_callable(
            lambda _event: (
                open_request.result.createObjectStore(query_response_indexeddb_store)
                if not open_request.result.objectStoreNames.contains(query_response_indexeddb_store)
                else None
            )
        )
        db = await request_as_promise(open_request)
        tx = db.transaction(query_response_indexeddb_store, 'readonly')
        store = tx.objectStore(query_response_indexeddb_store)
        response = await request_as_promise(store.get(query_id))
        await transaction_as_promise(tx)
        if response is not None:
            delete_tx = db.transaction(query_response_indexeddb_store, 'readwrite')
            delete_store = delete_tx.objectStore(query_response_indexeddb_store)
            await request_as_promise(delete_store.delete(query_id))
            await transaction_as_promise(delete_tx)
        db.close()
        return cast(Optional[str], response)

    return cast(Optional[str], run_sync(load()))


def supports_blocking_js_promise_wait() -> bool:
    global _run_sync_supported

    if _run_sync_supported is not None:
        return _run_sync_supported

    from pyodide.ffi import run_sync  # type: ignore

    async def probe() -> None:
        return None

    probe_coro = probe()
    try:
        run_sync(probe_coro)
    except RuntimeError as exc:
        probe_coro.close()
        if 'WebAssembly stack switching not supported' in str(exc):
            _run_sync_supported = False
            return False
        raise
    except Exception:
        probe_coro.close()
        raise

    _run_sync_supported = True
    return True


def request_as_promise(request):
    from pyodide.ffi import create_once_callable  # type: ignore
    import js  # type: ignore

    def executor(resolve, reject):
        request.onsuccess = create_once_callable(lambda _event: resolve(request.result))
        request.onerror = create_once_callable(lambda _event: reject(request.error))

    return js.Promise.new(create_once_callable(executor))


def transaction_as_promise(transaction):
    from pyodide.ffi import create_once_callable  # type: ignore
    import js  # type: ignore

    def executor(resolve, reject):
        transaction.oncomplete = create_once_callable(lambda _event: resolve(None))
        transaction.onerror = create_once_callable(lambda _event: reject(transaction.error))
        transaction.onabort = create_once_callable(lambda _event: reject(transaction.error))

    return js.Promise.new(create_once_callable(executor))

def create_comm(target: str, initial_msg):  # pragma: no cover
    f: Optional[Callable] = None
    if f is None:
        try:
            from comm import create_comm  # type: ignore

            f = create_comm
        except ImportError:
            pass
    if f is None:
        try:
            from ipykernel.comm import Comm  # type: ignore

            f = Comm
        except ImportError:
            pass
    if f is None:
        raise ImportError('No available comm module')
    return f(target, initial_msg)
