// typeValidators.js will be generated by jlpm run refresh-jsonschema && jlpm run refresh-type-validator
// @ts-ignore
import * as validators from './typeValidators'
import { JsonSchema } from './types'

export class TypeGuardError extends Error { }


export function catchTypeGuardError(cb: () => void) {
  try {
    cb()
  }
  catch (e) {
    console.log(e)
    if (e instanceof TypeGuardError) {
      alert(e.message)
    }
    else {
      throw e
    }
  }
}


function createAssert<MapName extends keyof JsonSchema>(mapName: MapName) {
  function assert<M extends keyof (JsonSchema[MapName])>(
    schemaName: M,
    obj: any,
  ): asserts obj is JsonSchema[MapName][M] {
    const validatorName = `${mapName}_${String(schemaName)}`
    // @ts-ignore
    const v = validators[validatorName]
    if (!v) {
      throw new Error(`Validator not found: ${validatorName}`)
    }
    if (!v(obj)) {
      console.error(obj)
      // @ts-ignore
      throw new TypeGuardError(`TypeError for ${schemaName}\n${JSON.stringify(v.errors, null, 2)}`)
    }
  }
  return assert
}


export const assertMessageToStellarGlobeType: <M extends keyof JsonSchema["MessageToJS"]>(
  schemaName: M,
  obj: any,
) => asserts obj is JsonSchema["MessageToJS"][M] = createAssert("MessageToJS")

export const assertLayerProps: <M extends keyof JsonSchema["LayerProps"]>(
  schemaName: M,
  obj: any,
) => asserts obj is JsonSchema["LayerProps"][M] = createAssert("LayerProps")
