import { MessageToStellarGlobe } from './MessageControllableGlobe/messageHandlers'
// typeValidators.js will be generated by jlpm run refresh-jsonschema && jlpm run refresh-type-validator
// @ts-ignore
import validators from './typeValidators'

class TypeGuardError extends Error { }


export function catchTypeGuardError(cb: () => void) {
  try {
    cb()
  }
  catch (e) {
    console.log(e)
    if (e instanceof TypeGuardError) {
      alert(e.message)
    }
    else {
      throw e
    }
  }
}


export type OpenWindowMessage = {
  id: string
  title?: string
}


function createAssert(path: keyof typeof validators) {
  // @ts-ignore
  const v = validators[path]
  return function (obj: any) {
    if (!v(obj)) {
      // @ts-ignore
      throw new TypeGuardError(`TypeError for ${path}\n${JSON.stringify(v.errors, null, 2)}`)
    }
  }
}

export const assertOpenWindowMessage: (obj: any) => asserts obj is OpenWindowMessage = createAssert("./jsonschema/MessageToJupyterLab/OpenWindowMessage.json")
export const assertMessageToStellarGlobe: (obj: any) => asserts obj is MessageToStellarGlobe = createAssert('./jsonschema/MessageToStellraGlobe.json')
