// typeValidators.js will be generated by jlpm run refresh-jsonschema
// @ts-ignore
import * as validators from './typeValidators'

export class TypeGuardError extends Error { }


export function catchTypeGuardError(cb: () => void) {
  try {
    cb()
  }
  catch (e) {
    console.log(e)
    if (e instanceof TypeGuardError) {
      alert(e.message)
    }
    else {
      throw e
    }
  }
}


export function createIs<Type>(validatorName: keyof typeof validators) {
  function is(
    obj: any,
  ): obj is Type {
    const v = validators[validatorName]
    if (!v) {
      throw new Error(`Validator not found: ${validatorName}`)
    }
    return v(obj)
  }
  return is
}


export function createAssert<ValidatorName extends keyof typeof validators, Type>(validatorName: ValidatorName) {
  function assert(
    obj: any,
  ): asserts obj is Type {
    const v = validators[validatorName]
    if (!v) {
      throw new Error(`Validator not found: ${validatorName}`)
    }
    if (!v(obj)) {
      console.error(obj)
      // @ts-ignore
      throw new TypeGuardError(`TypeError for ${validatorName}\n${JSON.stringify(v.errors, null, 2)}`)
    }
  }
  return assert
}
